/// <summary>
/// An enumeration of the audio clip names
/// </summary>
public enum AudioClipName
{
    none,
    menuClick,
    menuClickPlay,
    menuMusic,
    menuNavigation,
    basicAttack,
    basicAttack2,
    basicAttack3,
    specialAttackCharge,
    specialAttackFire,
    specialAttackImpact,
    playerLand,
    playerJump,
    spikesImpact,
    rockImpact,
    caveAmbiance,
    healthResource,
    music,
    theDevil,
    theEmperorImpact,
    theEmperorEarthquake,
    theEmpressCharge,
    theEmpressSmoke,
    theSunFire,
    theSunCharge,
    theSunImpact,
    theFool,
    tarotCardsMovement,
    tarotCardsReadingDeal,
    playerAttacked1,
    playerAttacked2,
    playerDeath,
    enemyDeath,
    groundedEnemyGrowl,
    flyingEnemyGrowl,
    flyingEnemyMissile,
    skillUnavailable,
    roomChange,
    levelCompleted,
    enemyAttacked,
    groundedEnemyAttack,
}   
